name: BATS

on: [push, pull_request]

jobs:
  bats:
    strategy:
      matrix:
        os: [macos-latest, macos-13]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: mig4/setup-bats@v1
      - name: Run tests
        run: |
          bats test