name: Brew Bundle (dry-run)

on:
  pull_request:
    paths: ["Brewfile"]

jobs:
  brewfile:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Dry‑run Brew Bundle
        run: |
          brew update
          brew bundle --file=./Brewfile --no-lock --verbose --dry-run