name: Install Tests

on:
  pull_request:
  push:

jobs:
  install-dry-run:
    name: Install (dry-run)
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Dry-run installer
        run: |
          chmod +x install.sh
          ./install.sh -n   # -n == dry-run

  install-full:
    name: Install (full)
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Full install test
        run: |
          chmod +x install.sh
          ./install.sh
      - name: Verify installation
        run: |
          # Check if key tools were installed
          command -v eza || echo "❌ eza not found"
          command -v bat || echo "❌ bat not found"
          command -v fd || echo "❌ fd not found"
          command -v rg || echo "❌ rg not found"
          command -v jq || echo "❌ jq not found"

          # Check if aliases file was created
          [ -f ~/.mac-dev-setup-aliases ] || echo "❌ aliases file not found"

          # Check if zsh config was created
          [ -f ~/.zsh_config.sh ] || echo "❌ zsh config not found"

          # Verify alias file contains expected aliases (without sourcing)
          grep -q "alias gs=" ~/.mac-dev-setup-aliases || echo "❌ gs alias not found in file"
          grep -q "alias k=" ~/.mac-dev-setup-aliases || echo "❌ k alias not found in file"
