name: Install Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  install-full:
    name: Full cycle test (uninstall → install → uninstall)
    runs-on: macos-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4

      - name: Initial cleanup (uninstall any existing setup)
        run: |
          # Run uninstall in case there's any existing setup
          echo "Running initial cleanup..."
          ./uninstall.sh --yes

      - name: Install mac-dev-setup
        run: |
          echo "Installing mac-dev-setup..."
          ./install.sh --yes

      - name: Test uninstall (final cleanup)
        run: |
          echo "Testing uninstall process..."
          ./uninstall.sh --yes
