name: Install (dry-run)

on:
  pull_request:
  push:

jobs:
  mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Dry-run installer
        run: |
          chmod +x install.sh
          ./install.sh -n   # -n == dry-run
