name: Shell Lint

on:
  push:
    paths: ["*.sh", "**/*.sh", ".github/workflows/shellcheck.yml"]
  pull_request:
    paths: ["*.sh", "**/*.sh"]

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ludeeus/action-shellcheck@2.0.0
        with:
          severity: warning