name: Test Installation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Test installation (simulate user input)
      run: echo "n" | ./install.sh || echo "Installation cancelled as expected"

    - name: Test brew task directly
      run: bash tasks/brew.install.sh --print

    - name: Test python task directly
      run: bash tasks/python.install.sh --print

    - name: Verify config files exist
      run: |
        test -f "Brewfile"
        test -f "pipx.txt"
        echo "✅ Config files found"

    - name: Test Brewfile syntax
      run: |
        ruby -c Brewfile
        echo "✅ Brewfile syntax valid"
